/**
 * Transport layer exports for Backend-Orchestrator communication
 */

export {
	type B2ORequest,
	type B2OResponse,
	B2O_CreateTaskRequestSchema,
	type B2O_CreateTaskRequest,
	B2O_GetTaskRequestSchema,
	type B2O_GetTaskRequest,
	B2O_GetTasksRequestSchema,
	type B2O_GetTasksRequest,
	B2O_GetWorkersRequestSchema,
	type B2O_GetWorkersRequest,
	B2O_RenameWorkerRequestSchema,
	type B2O_RenameWorkerRequest,
	B2O_GetStatsRequestSchema,
	type B2O_GetStatsRequest,
	B2O_UpdateConfigRequestSchema,
	type B2O_UpdateConfigRequest,
	type B2OMethods,
	B2O_REQUEST_SCHEMAS,
	validateB2ORequest,
} from './B2OContract.js';

export {
	O2B_WorkerStatusEventSchema,
	type O2B_WorkerStatusEvent,
	O2B_WorkerLogEventSchema,
	type O2B_WorkerLogEvent,
	O2B_WorkerConnectedEventSchema,
	type O2B_WorkerConnectedEvent,
	O2B_WorkerDisconnectedEventSchema,
	type O2B_WorkerDisconnectedEvent,
	O2B_TaskCreatedEventSchema,
	type O2B_TaskCreatedEvent,
	O2B_TaskUpdatedEventSchema,
	type O2B_TaskUpdatedEvent,
	O2B_TaskCompletedEventSchema,
	type O2B_TaskCompletedEvent,
	O2B_TaskFailedEventSchema,
	type O2B_TaskFailedEvent,
	O2B_TaskStatusChangedEventSchema,
	type O2B_TaskStatusChangedEvent,
	type O2BEvent,
	type O2BEventType,
	type O2BEventData,
	O2B_EVENT_SCHEMAS,
	validateO2BEvent,
} from './O2BEventTypes.js';
