#!/usr/bin/env node
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { HookConfig } from '../hooks/HookDispatcher.js';
import { HookDispatcher } from '../hooks/HookDispatcher.js';
import { isProjectInitialized, loadTaskConfig } from '../task/TaskConfigLoader.js';
import { TaskStore } from '../task/TaskStore.js';
import type { TaskStatus } from '../task/TaskStore.js';

const PROJECT_CONFIG_TEMPLATE = `# Task configuration for this project
# Generated by: task init

statuses:
  - backlog
  - in-progress
  - done

# fields:
#   - name: component
#     type: string
#     required: false

# defaults:
#   priority: medium

# hooks:
#   onTaskCreated: ""
#   onStatusChange: ""
`;

function parseHookCommand(cmd: string): HookConfig {
	const parts = cmd.trim().split(/\s+/);
	return { type: 'cli', command: parts[0]!, args: parts.slice(1) };
}

function buildHookDispatcher(
	globalHooks: Record<string, string>,
	projectHooks: Record<string, string>
): HookDispatcher {
	const combined: Record<string, HookConfig[]> = {};
	const allEvents = new Set([...Object.keys(globalHooks), ...Object.keys(projectHooks)]);
	for (const event of allEvents) {
		const list: HookConfig[] = [];
		const globalCmd = globalHooks[event];
		if (globalCmd) list.push(parseHookCommand(globalCmd));
		const projectCmd = projectHooks[event];
		if (projectCmd) list.push(parseHookCommand(projectCmd));
		if (list.length > 0) combined[event] = list;
	}
	return new HookDispatcher(combined);
}

function parseArgs(args: string[]): {
	configDir: string | undefined;
	command: string | undefined;
	rest: string[];
} {
	let i = 0;
	let configDir: string | undefined;

	if (args[i] === '--config' && args[i + 1] !== undefined) {
		configDir = args[i + 1]!;
		i += 2;
	}

	const command = args[i];
	const rest = args.slice(i + 1);
	return { configDir, command, rest };
}

export interface CommandResult {
	exitCode: number;
	output: string;
}

export async function runTaskCommand(args: string[], cwd: string): Promise<CommandResult> {
	const { configDir: configDirArg, command, rest } = parseArgs(args);

	if (!command || command === '--help') {
		return {
			exitCode: 0,
			output: 'Usage: task [--config <dir>] <init|new|list|show|approve|set-status>',
		};
	}

	if (command === 'init') {
		const taskDir = path.join(cwd, '.task');
		if (fs.existsSync(taskDir)) {
			return { exitCode: 0, output: 'Project already initialized.' };
		}
		fs.mkdirSync(path.join(taskDir, 'tasks'), { recursive: true });
		fs.writeFileSync(path.join(taskDir, 'config.yml'), PROJECT_CONFIG_TEMPLATE, 'utf8');
		return { exitCode: 0, output: `Initialized task project in ${taskDir}` };
	}

	if (!isProjectInitialized(cwd)) {
		return {
			exitCode: 1,
			output: JSON.stringify({ error: 'project not initialized, run: task init' }),
		};
	}

	const config = loadTaskConfig({ configDir: configDirArg, projectDir: cwd });
	const tasksDir = path.join(cwd, '.task', 'tasks');
	const store = new TaskStore(tasksDir);
	const hookDispatcher = buildHookDispatcher(config.globalHooks, config.projectHooks);

	const projectEnv = {
		taskProjectName: path.basename(cwd),
		taskProjectPath: cwd,
	};

	switch (command) {
		case 'new': {
			const description = rest[0];
			if (!description) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: 'Missing description. Usage: task new <description>' }),
				};
			}
			const task = store.create(description);
			await hookDispatcher.dispatch('onTaskCreated', {
				taskId: task.id,
				status: task.status,
				description: task.description,
				taskFile: path.join(tasksDir, `${task.id}.json`),
				...projectEnv,
			});
			return { exitCode: 0, output: JSON.stringify(task, null, 2) };
		}

		case 'list': {
			const tasks = store.list();
			return { exitCode: 0, output: JSON.stringify(tasks, null, 2) };
		}

		case 'show': {
			const id = rest[0];
			if (!id) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: 'Missing id. Usage: task show <id>' }),
				};
			}
			try {
				const task = store.get(id);
				return { exitCode: 0, output: JSON.stringify(task, null, 2) };
			} catch (error) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: (error as Error).message }),
				};
			}
		}

		case 'approve': {
			const id = rest[0];
			if (!id) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: 'Missing id. Usage: task approve <id>' }),
				};
			}
			try {
				const before = store.get(id);
				const updated = store.updateStatus(id, 'approved' as TaskStatus);
				await hookDispatcher.dispatch('onStatusChange', {
					taskId: updated.id,
					oldStatus: before.status,
					newStatus: updated.status,
					...projectEnv,
				});
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: (error as Error).message }),
				};
			}
		}

		case 'set-status': {
			const id = rest[0];
			const statusArg = rest[1];
			if (!id || !statusArg) {
				return {
					exitCode: 1,
					output: JSON.stringify({
						error: 'Missing arguments. Usage: task set-status <id> <status>',
					}),
				};
			}
			if (!config.statuses.includes(statusArg)) {
				return {
					exitCode: 1,
					output: JSON.stringify({
						error: `Invalid status: ${statusArg}. Valid values: ${config.statuses.join(', ')}`,
					}),
				};
			}
			try {
				const before = store.get(id);
				const updated = store.updateStatus(id, statusArg as TaskStatus);
				await hookDispatcher.dispatch('onStatusChange', {
					taskId: updated.id,
					oldStatus: before.status,
					newStatus: updated.status,
					...projectEnv,
				});
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return {
					exitCode: 1,
					output: JSON.stringify({ error: (error as Error).message }),
				};
			}
		}

		default:
			return {
				exitCode: 1,
				output: JSON.stringify({
					error: `Unknown command: ${command}. Valid commands: init, new, list, show, approve, set-status`,
				}),
			};
	}
}

async function main(): Promise<void> {
	const args = process.argv.slice(2);
	const { exitCode, output } = await runTaskCommand(args, process.cwd());
	if (exitCode === 0) {
		process.stdout.write(output + '\n');
	} else {
		process.stderr.write(output + '\n');
	}
	process.exit(exitCode);
}

const isEntryPoint =
	process.argv[1] !== undefined &&
	(process.argv[1] === fileURLToPath(import.meta.url) ||
		process.argv[1].endsWith('TaskIndex.js') ||
		process.argv[1].endsWith('TaskIndex.ts'));

if (isEntryPoint) {
	main().catch(error => {
		process.stderr.write(JSON.stringify({ error: String(error) }) + '\n');
		process.exit(1);
	});
}
