#!/usr/bin/env node
import { ConfigDir, UpdateManager } from '@wadeck-app/shared-cli';
import { logCliInvocation } from '@wadeck-app/shared-cli/CliLogger';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { execFileSync, execSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { TaskConfigLoader } from '../task/TaskConfigLoader.js';
import { TaskStore } from '../task/TaskStore.js';
import type { TaskStatus } from '../task/TaskStore.js';
import {
	printTaskCliHelp,
	runTaskCliRollback,
	runTaskCliSelfCheck,
	runTaskCliUpdate,
	runTaskCliVersion,
	runTaskCliLogs,
} from './commands/TaskCliCommand.js';
import { VERSION } from './version.js';

const PROJECT_CONFIG_TEMPLATE = `# Task configuration for this project
# Generated by: task init

statuses:
  - backlog
  - in-progress
  - done

# fields:
#   - name: component
#     type: string
#     required: false

# defaults:
#   priority: medium

# hooks:
#   onTaskCreated: ""
#   onStatusChange: ""
`;

function levenshtein(a: string, b: string): number {
	const m = a.length;
	const n = b.length;
	const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
		Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0))
	);
	for (let i = 1; i <= m; i++) {
		for (let j = 1; j <= n; j++) {
			dp[i]![j] =
				a[i - 1] === b[j - 1]
					? dp[i - 1]![j - 1]!
					: 1 + Math.min(dp[i - 1]![j]!, dp[i]![j - 1]!, dp[i - 1]![j - 1]!);
		}
	}
	return dp[m]![n]!;
}

function suggest(input: string, candidates: string[]): string | undefined {
	let best: string | undefined;
	let bestDist = Infinity;
	for (const c of candidates) {
		const d = levenshtein(input.toLowerCase(), c.toLowerCase());
		if (d < bestDist) {
			bestDist = d;
			best = c;
		}
	}
	return bestDist <= 3 ? best : undefined;
}

// Lazily resolved path to queue's JS entry point — avoids shell and quoting issues.
let _queueJsPath: string | undefined;
function resolveQueueJsPath(): string {
	if (_queueJsPath) return _queueJsPath;
	// On Windows, use 'where queue.cmd' via shell to get a native Windows path.
	// On Unix, use 'which queue' to get the script path.
	let nativeDir: string;
	if (process.platform === 'win32') {
		const winPath = execSync('where queue.cmd', { encoding: 'utf8', windowsHide: true }).trim().split('\n')[0]!.trim();
		nativeDir = path.dirname(winPath);
	} else {
		nativeDir = path.dirname(execFileSync('which', ['queue'], { encoding: 'utf8' }).trim());
	}
	_queueJsPath = path.join(nativeDir, 'node_modules', '@wadeck-app', 'queue-cli', 'bin', 'queue.js');
	return _queueJsPath;
}

async function pushToQueue(event: string, payload: Record<string, unknown>): Promise<void> {
	const json = JSON.stringify(payload);
	let queueJs: string;
	try {
		queueJs = resolveQueueJsPath();
	} catch {
		process.stderr.write(`[task] queue not found on PATH — event '${event}' not delivered\n`);
		return;
	}
	// Spawn node directly with queue.js — no shell, args passed verbatim (no JSON quoting issues).
	await new Promise<void>((resolve) => {
		// violations-suppress: cli/no-spawn-without-windows-hide stdio:inherit passes terminal to queue CLI intentionally
		const child = spawn(process.execPath, [queueJs, 'push', event, json], { stdio: 'inherit' });
		child.on('close', (code) => {
			if (code !== 0) {
				process.stderr.write(`[task] queue push '${event}' failed (exit ${code}) — event not delivered\n`);
			}
			resolve();
		});
		child.on('error', (err) => {
			process.stderr.write(`[task] queue push '${event}' error: ${(err as Error).message}\n`);
			resolve();
		});
	});
}

function parseArgs(args: string[]): {
	configDir: string | undefined;
	projectDir: string | undefined;
	jsonMode: boolean;
	command: string | undefined;
	rest: string[];
} {
	let i = 0;
	let configDir: string | undefined;
	let projectDir: string | undefined;
	let jsonMode = false;

	while (i < args.length) {
		if (args[i] === '--config' && args[i + 1] !== undefined) {
			configDir = args[i + 1]!;
			i += 2;
		} else if (args[i] === '--json') {
			jsonMode = true;
			i++;
		} else {
			break;
		}
	}

	const command = args[i];
	const trailing = args.slice(i + 1);

	// Filter --project-dir <path> and --json from rest args
	const rest: string[] = [];
	for (let j = 0; j < trailing.length; j++) {
		if (trailing[j] === '--project-dir' && trailing[j + 1] !== undefined) {
			projectDir = trailing[j + 1]!;
			j++;
		} else if (trailing[j] === '--json') {
			jsonMode = true;
		} else {
			rest.push(trailing[j]!);
		}
	}

	return { configDir, projectDir, jsonMode, command, rest };
}

export interface CommandResult {
	exitCode: number;
	output: string;
}

function errorOutput(jsonMode: boolean, message: string, hint?: string): CommandResult {
	if (jsonMode) {
		return { exitCode: 1, output: JSON.stringify({ error: message }) };
	}
	const lines = [`Error: ${message}`];
	if (hint) lines.push(hint);
	return { exitCode: 1, output: lines.join('\n') };
}

export async function runTaskCommand(args: string[], cwd: string): Promise<CommandResult> {
	const { configDir: configDirArg, projectDir: projectDirArg, jsonMode, command, rest } = parseArgs(args);
	const effectiveProjectDir = projectDirArg ?? process.env['TASK_PROJECT_DIR'] ?? process.env['PROJECT_DIR'];
	const effectiveCwd = effectiveProjectDir ? path.resolve(cwd, effectiveProjectDir) : cwd;

	// Log every CLI invocation to ~/.config/task/logs/YYYY-MM-DD.ndjson
	try { logCliInvocation(ConfigDir.get('task'), 'task', args); } catch { /* never block the CLI on logging failure */ }

	// Show update notice from a previous background update run
	const updateManager = new UpdateManager('@wadeck-app/task-cli');
	const updateState = updateManager.readAndClearState();
	if (updateState?.status === 'success') {
		process.stderr.write(`[task] Updated to v${updateState.targetVersion ?? updateState.newVersion}\n`);
	}
	if (updateState?.status === 'rolled-back') {
		process.stderr.write(
			`[task] Update to v${updateState.targetVersion} failed (self-check failed). Rolled back to v${updateState.previousVersion}. Run: task cli update --log\n`
		);
	}
	if (updateState?.status === 'failed') {
		process.stderr.write(`[task] Background update failed (${updateState.error ?? updateState.reason}). Run: task cli update\n`);
	}

	if (!command || command === '--help') {
		return {
			exitCode: 0,
			output: 'Usage: task [--config <dir>] [--json] <init|new|list|show|set-status|set-type|add-label|remove-label|set-meta>',
		};
	}

	if (command === '--version' || command === '-V') {
		return { exitCode: 0, output: VERSION };
	}

	if (command === 'init') {
		const taskDir = path.join(effectiveCwd, '.task');
		if (fs.existsSync(taskDir)) {
			return { exitCode: 0, output: 'Project already initialized.' };
		}
		fs.mkdirSync(path.join(taskDir, 'tasks'), { recursive: true });
		fs.writeFileSync(path.join(taskDir, 'config.yml'), PROJECT_CONFIG_TEMPLATE, 'utf8');
		return { exitCode: 0, output: `Initialized task project in ${taskDir}` };
	}

	if (command === 'cli') {
		const subCmd = rest[0];
		switch (subCmd) {
			case 'version':
				await runTaskCliVersion();
				return { exitCode: 0, output: '' };
			case 'update': {
				const hasCheck = rest.includes('--check');
				const hasLog = rest.includes('--log');
				await runTaskCliUpdate({ check: hasCheck, log: hasLog, rawArgs: rest });
				return { exitCode: 0, output: '' };
			}
			case 'rollback':
				await runTaskCliRollback();
				return { exitCode: 0, output: '' };
			case 'self-check':
				await runTaskCliSelfCheck();
				return { exitCode: 0, output: '' };
			case 'logs': {
				const follow = rest.includes('--follow');
				await runTaskCliLogs({ follow });
				return { exitCode: 0, output: '' };
			}
			case undefined:
			case '--help':
			case 'help':
				printTaskCliHelp();
				return { exitCode: 0, output: '' };
			default:
				return errorOutput(
					jsonMode,
					`unknown task cli subcommand: ${subCmd}`,
					'Valid subcommands: version, update, rollback, self-check, logs'
				);
		}
	}

	if (!TaskConfigLoader.isInitialized(effectiveCwd)) {
		return errorOutput(jsonMode, 'project not initialized', 'Run: task init');
	}

	const config = TaskConfigLoader.load({ configDir: configDirArg, projectDir: effectiveCwd });
	const tasksDir = path.join(effectiveCwd, '.task', 'tasks');
	const store = new TaskStore(tasksDir);

	const projectEnv = {
		taskProjectName: path.basename(effectiveCwd),
		taskProjectPath: effectiveCwd,
	};

	switch (command) {
		case 'new': {
			const description = rest[0];
			if (!description) {
				return errorOutput(jsonMode, 'missing description', 'Usage: task new <description>');
			}
			const task = store.create(description);
			await pushToQueue('onTaskCreated', {
				taskId: task.id,
				status: task.status,
				description: task.description,
				type: task.type,
				labels: task.labels ?? [],
				...projectEnv,
			});
			return { exitCode: 0, output: JSON.stringify(task, null, 2) };
		}

		case 'list': {
			const tasks = store.list();
			return { exitCode: 0, output: JSON.stringify(tasks, null, 2) };
		}

		case 'show': {
			const id = rest[0];
			if (!id) {
				return errorOutput(jsonMode, 'missing id', 'Usage: task show <id>');
			}
			try {
				const task = store.findByPrefix(id);
				return { exitCode: 0, output: JSON.stringify(task, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'set-status': {
			const id = rest[0];
			const statusArg = rest[1];
			if (!id || !statusArg) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task set-status <id> <status>');
			}
			if (!config.statuses.includes(statusArg)) {
				const hint = suggest(statusArg, config.statuses);
				const validLine = `Valid statuses: ${config.statuses.join(', ')}`;
				const hintLine = hint ? `\nDid you mean: ${hint}?` : '';
				if (jsonMode) {
					return {
						exitCode: 1,
						output: JSON.stringify({
							error: `Invalid status: ${statusArg}. Valid values: ${config.statuses.join(', ')}`,
						}),
					};
				}
				return {
					exitCode: 1,
					output: `Error: unknown status "${statusArg}"\n${validLine}${hintLine}`,
				};
			}
			try {
				const before = store.findByPrefix(id);
				const updated = store.updateStatus(before.id, statusArg as TaskStatus, before);
				await pushToQueue('onStatusChange', {
					taskId: updated.id,
					oldStatus: before.status,
					newStatus: updated.status,
					type: updated.type,
					labels: updated.labels ?? [],
					...projectEnv,
				});
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'set-type': {
			const id = rest[0];
			const type = rest[1];
			if (!id || !type) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task set-type <id> <type>');
			}
			try {
				const updated = store.setType(store.findByPrefix(id).id, type);
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'add-label': {
			const id = rest[0];
			const label = rest[1];
			if (!id || !label) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task add-label <id> <label>');
			}
			try {
				const updated = store.addLabel(store.findByPrefix(id).id, label);
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'remove-label': {
			const id = rest[0];
			const label = rest[1];
			if (!id || !label) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task remove-label <id> <label>');
			}
			try {
				const updated = store.removeLabel(store.findByPrefix(id).id, label);
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'set-meta': {
			const id = rest[0];
			const key = rest[1];
			const value = rest[2];
			if (!id || !key || value === undefined) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task set-meta <id> <key> <value>');
			}
			try {
				const updated = store.setMeta(store.findByPrefix(id).id, key, value);
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		default:
			return errorOutput(
				jsonMode,
				`unknown command: ${command}`,
				'Valid commands: init, new, list, show, set-status, set-type, add-label, remove-label, set-meta'
			);
	}
}

async function main(): Promise<void> {
	const args = process.argv.slice(2);
	const { exitCode, output } = await runTaskCommand(args, process.cwd());
	if (exitCode === 0) {
		if (output.length > 0) process.stdout.write(output + '\n');
	} else {
		if (output.length > 0) process.stderr.write(output + '\n');
	}

	// Schedule background updater after command completes
	const bundlePath = process.env['LAUNCHER_BUNDLE_OVERRIDE'] ?? fileURLToPath(import.meta.url);
	new UpdateManager('@wadeck-app/task-cli').scheduleBackgroundUpdate(bundlePath, 'task-updater.cjs');

	process.exit(exitCode);
}

const isEntryPoint =
	process.argv[1] !== undefined &&
	(process.argv[1] === fileURLToPath(import.meta.url) ||
		process.argv[1].endsWith('TaskIndex.js') ||
		process.argv[1].endsWith('TaskIndex.ts'));

if (isEntryPoint) {
	main().catch(error => {
		process.stderr.write(`Error: ${String(error)}\n`);
		process.exit(1);
	});
}
