#!/usr/bin/env node
import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import type { HookConfig } from 'shared-cli/HookDispatcher';
import { HookDispatcher, UpdateManager } from 'shared-cli/index';
import { TaskConfigLoader } from '../task/TaskConfigLoader.js';
import type { TaskHookValue } from '../task/TaskConfigLoader.js';
import { TaskStore } from '../task/TaskStore.js';
import type { TaskStatus } from '../task/TaskStore.js';
import {
	printTaskCliHelp,
	runTaskCliRollback,
	runTaskCliSelfCheck,
	runTaskCliUpdate,
	runTaskCliVersion,
} from './commands/TaskCliCommand.js';

// Injected by esbuild at bundle time; falls back to package.json in dev mode (tsx).
declare const __TASK_CLI_VERSION__: string;

const PROJECT_CONFIG_TEMPLATE = `# Task configuration for this project
# Generated by: task init

statuses:
  - backlog
  - in-progress
  - done

# fields:
#   - name: component
#     type: string
#     required: false

# defaults:
#   priority: medium

# hooks:
#   onTaskCreated: ""
#   onStatusChange: ""
`;

function levenshtein(a: string, b: string): number {
	const m = a.length;
	const n = b.length;
	const dp: number[][] = Array.from({ length: m + 1 }, (_, i) =>
		Array.from({ length: n + 1 }, (_, j) => (i === 0 ? j : j === 0 ? i : 0))
	);
	for (let i = 1; i <= m; i++) {
		for (let j = 1; j <= n; j++) {
			dp[i]![j] =
				a[i - 1] === b[j - 1]
					? dp[i - 1]![j - 1]!
					: 1 + Math.min(dp[i - 1]![j]!, dp[i]![j - 1]!, dp[i - 1]![j - 1]!);
		}
	}
	return dp[m]![n]!;
}

function suggest(input: string, candidates: string[]): string | undefined {
	let best: string | undefined;
	let bestDist = Infinity;
	for (const c of candidates) {
		const d = levenshtein(input.toLowerCase(), c.toLowerCase());
		if (d < bestDist) {
			bestDist = d;
			best = c;
		}
	}
	return bestDist <= 3 ? best : undefined;
}

function parseHookCommand(value: TaskHookValue): HookConfig {
	const raw = typeof value === 'string' ? value : value.command;
	const debug = typeof value === 'object' ? value.debug : undefined;
	const parts = raw.trim().split(/\s+/);
	if (!parts[0]) {
		throw new Error(`Hook command cannot be empty. Got: "${raw}"`);
	}
	return { type: 'cli', command: parts[0], args: parts.slice(1), ...(debug !== undefined && { debug }) };
}

function buildHookDispatcher(
	globalHooks: Record<string, TaskHookValue>,
	projectHooks: Record<string, TaskHookValue>
): HookDispatcher {
	const combined: Record<string, HookConfig[]> = {};
	const allEvents = new Set([...Object.keys(globalHooks), ...Object.keys(projectHooks)]);
	for (const event of allEvents) {
		const list: HookConfig[] = [];
		const globalCmd = globalHooks[event];
		if (globalCmd) list.push(parseHookCommand(globalCmd));
		const projectCmd = projectHooks[event];
		if (projectCmd) list.push(parseHookCommand(projectCmd));
		if (list.length > 0) combined[event] = list;
	}
	return new HookDispatcher(combined);
}

function parseArgs(args: string[]): {
	configDir: string | undefined;
	projectDir: string | undefined;
	jsonMode: boolean;
	command: string | undefined;
	rest: string[];
} {
	let i = 0;
	let configDir: string | undefined;
	let projectDir: string | undefined;
	let jsonMode = false;

	while (i < args.length) {
		if (args[i] === '--config' && args[i + 1] !== undefined) {
			configDir = args[i + 1]!;
			i += 2;
		} else if (args[i] === '--json') {
			jsonMode = true;
			i++;
		} else {
			break;
		}
	}

	const command = args[i];
	const trailing = args.slice(i + 1);

	// Filter --project-dir <path> and --json from rest args
	const rest: string[] = [];
	for (let j = 0; j < trailing.length; j++) {
		if (trailing[j] === '--project-dir' && trailing[j + 1] !== undefined) {
			projectDir = trailing[j + 1]!;
			j++;
		} else if (trailing[j] === '--json') {
			jsonMode = true;
		} else {
			rest.push(trailing[j]!);
		}
	}

	return { configDir, projectDir, jsonMode, command, rest };
}

export interface CommandResult {
	exitCode: number;
	output: string;
}

function errorOutput(jsonMode: boolean, message: string, hint?: string): CommandResult {
	if (jsonMode) {
		return { exitCode: 1, output: JSON.stringify({ error: message }) };
	}
	const lines = [`Error: ${message}`];
	if (hint) lines.push(hint);
	return { exitCode: 1, output: lines.join('\n') };
}

export async function runTaskCommand(args: string[], cwd: string): Promise<CommandResult> {
	const { configDir: configDirArg, projectDir: projectDirArg, jsonMode, command, rest } = parseArgs(args);
	const effectiveProjectDir = projectDirArg ?? process.env['TASK_PROJECT_DIR'] ?? process.env['PROJECT_DIR'];
	const effectiveCwd = effectiveProjectDir ? path.resolve(cwd, effectiveProjectDir) : cwd;

	// Show update notice from a previous background update run
	const updateManager = new UpdateManager('@wadeck/task-cli');
	const updateState = updateManager.readAndClearState();
	if (updateState?.status === 'success') {
		process.stderr.write(`[task] Updated to v${updateState.newVersion}\n`);
	}
	if (updateState?.status === 'rolled-back') {
		process.stderr.write(
			`[task] Update to v${updateState.targetVersion} failed (self-check failed). Rolled back to v${updateState.previousVersion}. Run: task cli update --log\n`
		);
	}
	if (updateState?.status === 'update-failed') {
		process.stderr.write(`[task] Update check failed (${updateState.reason}). Run: task cli update\n`);
	}

	if (!command || command === '--help') {
		return {
			exitCode: 0,
			output: 'Usage: task [--config <dir>] [--json] <init|new|list|show|set-status>',
		};
	}

	if (command === '--version' || command === '-V') {
		let version: string;
		try {
			version = __TASK_CLI_VERSION__;
		} catch {
			const require = createRequire(import.meta.url);
			version = (require('../../package.json') as { version: string }).version;
		}
		return { exitCode: 0, output: version };
	}

	if (command === 'init') {
		const taskDir = path.join(effectiveCwd, '.task');
		if (fs.existsSync(taskDir)) {
			return { exitCode: 0, output: 'Project already initialized.' };
		}
		fs.mkdirSync(path.join(taskDir, 'tasks'), { recursive: true });
		fs.writeFileSync(path.join(taskDir, 'config.yml'), PROJECT_CONFIG_TEMPLATE, 'utf8');
		return { exitCode: 0, output: `Initialized task project in ${taskDir}` };
	}

	if (command === 'cli') {
		const subCmd = rest[0];
		switch (subCmd) {
			case 'version':
				await runTaskCliVersion();
				return { exitCode: 0, output: '' };
			case 'update': {
				const hasCheck = rest.includes('--check');
				const hasLog = rest.includes('--log');
				await runTaskCliUpdate({ check: hasCheck, log: hasLog });
				return { exitCode: 0, output: '' };
			}
			case 'rollback':
				runTaskCliRollback();
				return { exitCode: 0, output: '' };
			case 'self-check':
				await runTaskCliSelfCheck();
				return { exitCode: 0, output: '' };
			case undefined:
			case '--help':
			case 'help':
				printTaskCliHelp();
				return { exitCode: 0, output: '' };
			default:
				return errorOutput(
					jsonMode,
					`unknown task cli subcommand: ${subCmd}`,
					'Valid subcommands: version, update, rollback, self-check'
				);
		}
	}

	if (!TaskConfigLoader.isInitialized(effectiveCwd)) {
		return errorOutput(jsonMode, 'project not initialized', 'Run: task init');
	}

	const config = TaskConfigLoader.load({ configDir: configDirArg, projectDir: effectiveCwd });
	const tasksDir = path.join(effectiveCwd, '.task', 'tasks');
	const store = new TaskStore(tasksDir);
	const hookDispatcher = buildHookDispatcher(config.globalHooks, config.projectHooks);

	const projectEnv = {
		taskProjectName: path.basename(effectiveCwd),
		taskProjectPath: effectiveCwd,
	};

	switch (command) {
		case 'new': {
			const description = rest[0];
			if (!description) {
				return errorOutput(jsonMode, 'missing description', 'Usage: task new <description>');
			}
			const task = store.create(description);
			await hookDispatcher.dispatch(
				'onTaskCreated',
				{
					taskId: task.id,
					status: task.status,
					description: task.description,
					taskFile: path.join(tasksDir, `${task.id}.json`),
					...projectEnv,
				},
				() => process.stderr.write(`[task] hook 'onTaskCreated' failed\n`)
			);
			return { exitCode: 0, output: JSON.stringify(task, null, 2) };
		}

		case 'list': {
			const tasks = store.list();
			return { exitCode: 0, output: JSON.stringify(tasks, null, 2) };
		}

		case 'show': {
			const id = rest[0];
			if (!id) {
				return errorOutput(jsonMode, 'missing id', 'Usage: task show <id>');
			}
			try {
				const task = store.findByPrefix(id);
				return { exitCode: 0, output: JSON.stringify(task, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		case 'set-status': {
			const id = rest[0];
			const statusArg = rest[1];
			if (!id || !statusArg) {
				return errorOutput(jsonMode, 'missing arguments', 'Usage: task set-status <id> <status>');
			}
			if (!config.statuses.includes(statusArg)) {
				const hint = suggest(statusArg, config.statuses);
				const validLine = `Valid statuses: ${config.statuses.join(', ')}`;
				const hintLine = hint ? `\nDid you mean: ${hint}?` : '';
				if (jsonMode) {
					return {
						exitCode: 1,
						output: JSON.stringify({
							error: `Invalid status: ${statusArg}. Valid values: ${config.statuses.join(', ')}`,
						}),
					};
				}
				return {
					exitCode: 1,
					output: `Error: unknown status "${statusArg}"\n${validLine}${hintLine}`,
				};
			}
			try {
				const before = store.findByPrefix(id);
				const updated = store.updateStatus(before.id, statusArg as TaskStatus);
				await hookDispatcher.dispatch(
					'onStatusChange',
					{
						taskId: updated.id,
						oldStatus: before.status,
						newStatus: updated.status,
						...projectEnv,
					},
					() => process.stderr.write(`[task] hook 'onStatusChange' failed\n`)
				);
				return { exitCode: 0, output: JSON.stringify(updated, null, 2) };
			} catch (error) {
				return errorOutput(jsonMode, (error as Error).message);
			}
		}

		default:
			return errorOutput(
				jsonMode,
				`unknown command: ${command}`,
				'Valid commands: init, new, list, show, set-status'
			);
	}
}

async function main(): Promise<void> {
	const args = process.argv.slice(2);
	const { exitCode, output } = await runTaskCommand(args, process.cwd());
	if (exitCode === 0) {
		process.stdout.write(output + '\n');
	} else {
		process.stderr.write(output + '\n');
	}

	// Schedule background updater after command completes
	const bundlePath = process.env['LAUNCHER_BUNDLE_OVERRIDE'] ?? fileURLToPath(import.meta.url);
	new UpdateManager('@wadeck/task-cli').scheduleBackgroundUpdate(bundlePath, 'task-updater.cjs');

	process.exit(exitCode);
}

const isEntryPoint =
	process.argv[1] !== undefined &&
	(process.argv[1] === fileURLToPath(import.meta.url) ||
		process.argv[1].endsWith('TaskIndex.js') ||
		process.argv[1].endsWith('TaskIndex.ts'));

if (isEntryPoint) {
	main().catch(error => {
		process.stderr.write(`Error: ${String(error)}\n`);
		process.exit(1);
	});
}
