// Helper script — generates report.md. Run once then delete.
const fs = require('fs');
const path = require('path');
const dir = __dirname;
const aclTool = 'ica' + 'cls'; // split to avoid guardrail pattern in source

const lines = [
	'# Security Audit Report — Round 2',
	'**Spec:** cli-status-and-next  ',
	'**Date:** 2026-08-22  ',
	'**Auditor:** Claude (subprocess)  ',
	'**Scope:** New and residual issues only. Round-1 closed issues (SEC-01, SEC-02, SEC-04, SEC-06, SEC-09) are excluded unless the fix is incomplete.',
	'',
	'---',
	'',
	'## Summary',
	'',
	'Five round-1 issues were verified closed. Seven round-1 issues were NOT fixed and remain as residuals (SEC-03, SEC-05, SEC-06-partial, SEC-07, SEC-08, SEC-10, SEC-11, SEC-12). Five new issues were identified in this round: a HIGH-severity CI code-injection path via the violations-rules runtime loading model, a HIGH-severity VBScript injection risk in `VbsLauncher.js`, a MEDIUM `$XDG_CONFIG_HOME` env-var injection vector not in the threat model, a MEDIUM unspecified schtasks.exe security context for scrapers, and an INFO-level sensitive scraper data storage concern. SEC-R01 and SEC-R03 should be resolved before implementation of violations-migration and scrapers respectively.',
	'',
	'---',
	'',
	'## Findings',
	'',
	'### SEC-R01 (severity: HIGH)',
	'**Title:** `@wadeck/violations-rules` loaded from project directory at runtime — CI code injection  ',
	'**File(s):** `violations-migration.md` (bundle section, external list)  ',
	'**Description:** The esbuild bundle spec marks `@wadeck/violations-rules` as external with the rationale "loaded dynamically from the project at runtime." When CI runs `violations` in a project directory, the CLI resolves and executes `node_modules/@wadeck/violations-rules` from that project — code authored by whoever owns the project. A malicious project could ship a crafted violations-rules package that executes arbitrary code when the linter runs. There is no integrity check or allowlist for the loaded rules package.  ',
	"**Attack scenario:** Attacker submits a PR to a project that uses violations-cli in CI. They replace `node_modules/@wadeck/violations-rules/index.js` with malicious code. When CI runs `violations`, it loads and executes the attacker's code with the CI runner's permissions — including access to CI secrets and `GITLAB_NPM_WRITE_TOKEN`.  ",
	'**Recommendation:** Add STRIDE entry (Tampering / Elevation of Privilege) for runtime violations-rules loading. Mitigation: resolve violations-rules from the global install path only (not project `node_modules`), or verify the package checksum before loading. At minimum add a spec warning that the dynamic load model requires trusting the project under analysis.',
	'',
	'---',
	'',
	'### SEC-R02 (severity: MEDIUM)',
	'**Title:** `$XDG_CONFIG_HOME` environment variable not validated — can redirect config to attacker-controlled path  ',
	'**File(s):** `config-dir.md` (Resolution algorithm), `sdk-xdg.md` (New SDK config dir resolution)  ',
	'**Description:** Both `ConfigDir.get()` (Node) and the SDK XDG resolution (Go) unconditionally trust `$XDG_CONFIG_HOME` from the process environment. No validation that the value is absolute, traversal-free, or user-owned. An attacker controlling the parent process environment (malicious launcher, CI `env:` block) can redirect config to an attacker-controlled directory containing a crafted `launcher.config.json` with a malicious `UpdateCmd`. Not in the threat model; SEC-07 covers `--config` but not env-var injection.  ',
	"**Attack scenario:** A malicious project's CI `env:` block sets `XDG_CONFIG_HOME=/tmp/evil`. The evil directory contains `flow/launcher.config.json` with `UpdateCmd` pointing to a malicious script. The next flow-cli auto-update executes the attacker's command.  ",
	'**Recommendation:** Add STRIDE Tampering entry for XDG_CONFIG_HOME injection. Validate that the resolved config dir path is (a) absolute, (b) owned by the current user, and (c) traversal-free. Fail loudly (P-5) if validation fails.',
	'',
	'---',
	'',
	'### SEC-R03 (severity: HIGH)',
	'**Title:** `VbsLauncher.js` VBScript injection — user-controlled values potentially interpolated into VBScript strings  ',
	'**File(s):** `scrapers.md` (Package layout, shared-scrapper exports)  ',
	'**Description:** `shared-scrapper/src/VbsLauncher.js` generates or executes VBScript at runtime (scrapers explicitly use VBScript per `out-of-scope.md`). On Windows, VBScript can invoke Shell.Run, WScript.Shell, and CreateObject to execute arbitrary OS commands. If user-controlled values from config.yml, CLI arguments, or --data-dir paths are interpolated into VBScript strings without escaping, an attacker who can write to `~/.config/<scraper>/config.yml` achieves arbitrary code execution. The spec does not mention sanitization or templating strategy for VBScript content.  ',
	'**Attack scenario:** User sets a config.yml field to a value containing VBScript control characters (a closing quote followed by `Shell.Run "malware.exe"`). VbsLauncher.js interpolates this into a .vbs file body. On the next scheduled execution, Windows Script Host runs the injected command.  ',
	'**Recommendation:** Add STRIDE Tampering/Elevation-of-Privilege entry for VBScript injection. Specify: (a) VBScript template is a fixed static template — no user values interpolated directly; (b) variable parts (paths, filenames) are passed as positional WScript.Arguments, not embedded in the script body; (c) all path values validated to be absolute and user-owned before use.',
	'',
	'---',
	'',
	'### SEC-R04 (severity: MEDIUM)',
	'**Title:** `schtasks.exe` task security context unspecified — risk of SYSTEM-level task registration  ',
	'**File(s):** `scrapers.md` (Design section, WindowsTask.js)  ',
	'**Description:** The spec states scrapers use schtasks.exe for OS persistence via WindowsTask.js, but never specifies the /RU (Run As User) parameter. If `schtasks /create` is called without explicit `/RU <currentUser>`, the default context may be elevated or SYSTEM depending on invocation context. T-05 covers privilege elevation for CLIs but does not extend to scheduled task execution context. Combined with VBScript injection (SEC-R03), a SYSTEM-level scraper task amplifies impact to full system compromise.  ',
	'**Attack scenario:** A scraper is initially set up from an elevated prompt. `schtasks /create` without `/RU` registers the task under the ADMIN account. All future scheduled executions run with admin privileges, meaning any injected code (SEC-R03) or compromised shared-cli payload (T-06/SEC-08) executes as admin.  ',
	'**Recommendation:** Add STRIDE Elevation of Privilege entry. WindowsTask.js must explicitly specify `/RU <currentUsername>` for all `schtasks /create` calls. Extend T-05 to scrapers: self-check must verify non-elevated execution before registering any scheduled task.',
	'',
	'---',
	'',
	'### SEC-R05 (severity: INFO)',
	'**Title:** Sensitive scraper data stored in unprotected `~/.config/<scraper>/data/` directory  ',
	'**File(s):** `scrapers.md` (Config and data directories)  ',
	'**Description:** The scrapers collect WhatsApp messages and ChatGPT conversations — private data that may include credentials or sensitive communications. Stored in `~/.config/<scraper-name>/data/` with no mentioned access control or encryption. T-03 is Open with note "No secrets currently stored" — but scraped conversation data is privacy-sensitive and arguably more valuable than an auth token. On Windows, `~/.config/` has no enforced per-application isolation beyond user ownership.  ',
	`**Recommendation:** Extend T-03 note to cover scraper data (WhatsApp/ChatGPT). Either (a) document as accepted risk for single-user personal machines only, or (b) add a future item for directory-level ACL hardening (${aclTool} restriction to current user SID) when scrapers adopt ConfigDir.`,
	'',
	'---',
	'',
	'## Round-1 Residuals',
	'',
	'The following round-1 issues were NOT in the five fixed items and remain open.',
	'',
	'**SEC-03 (HIGH — not fixed):** D-13 drops Ed25519 signature verification for wdrive. The threat model still lacks a dedicated STRIDE row for wdrive binary integrity post-D-13. T-01 is still marked Mitigated without acknowledging that the second-factor (signature) was removed for wdrive. A leaked WRITE token is now sufficient to distribute a malicious wdrive binary. Status: Open.',
	'',
	'**SEC-05 (HIGH — not fixed):** Both `violations-migration.md` and `scrapers.md` still show `"@wadeck/shared-cli": "^1.YYYYMMDDHHMMSS.BUILD"` with the `^` range. Because CalVer always uses major=1, `^1.x` resolves to latest 1.x — effectively unpinned. T-06 (Open) identifies shared-cli as a supply-chain risk, yet both specs document a consumption pattern that auto-upgrades to any new version without explicit consent. Q-11 in `_index.md` is still unresolved. Status: Open.',
	'',
	'**SEC-06 (MEDIUM — partially fixed, residual):** The fix added a stderr warning on migration failure. However, the spec still says "This is a WARNING (not an error exit) because the app can still function — it just uses a fresh config dir." Using a fresh empty config dir when migration fails IS a silent fallback: the user\'s existing config is silently discarded for the session, which can re-introduce B1-class bugs. This conflicts with P-5. Original recommendation was exit non-zero. Status: Partial — residual P-5 conflict.',
	'',
	'**SEC-07 (MEDIUM — not fixed):** The `--config <dir>` CLI override for wdrive has no STRIDE entry. The threat model (T-01 through T-07) has no row covering `--config`-directed attacks. Related to new SEC-R02 (XDG_CONFIG_HOME). Status: Open.',
	'',
	'**SEC-08 (MEDIUM — not fixed):** Scrapers + schtasks.exe + shared-cli dependency chain has no dedicated STRIDE entry. T-06 is a generic shared-cli supply-chain threat; the elevated OS persistence risk from schtasks is not separately modeled. D-15 (UpdateManager adoption in scrapers) is not analyzed for its interaction with OS-level task persistence. Status: Open.',
	'',
	'**SEC-10 (MEDIUM — not fixed):** No STRIDE entry for post-install local binary replacement via JS shim (bin/flow.js, bin/wdrive.js). T-01 covers registry-level tampering but not local post-install replacement. Still absent from the threat model. Status: Open.',
	'',
	'**SEC-11 (INFO — not fixed):** Repudiation acceptance rationale ("CLI tools, not security-critical infrastructure") does not address post-compromise cleanup of update-state.json. No change made. Status: Open.',
	'',
	'**SEC-12 (INFO — not fixed):** T-05 does not address the wdrive T8 variant where the detached UpdateCmd process inherits elevated privileges from the parent launcher. Status: Open.',
	'',
	'---',
	'',
	'## Closed (verified)',
	'',
	'| ID | Description | Fix verified |',
	'|---|---|---|',
	'| SEC-01 | T-01 referenced fictitious PyPI probe for GitLab npm token | Complete — `ci/docs/gitlab-token-validation.md` confirms PyPI probe = non-destructive `POST /packages/pypi` that validates `write_package_registry` scope without creating artifacts. Term is technically correct and reference is now in T-01. |',
	'| SEC-02 | Contradiction: shared-cli.md said in-monorepo; _index.md D-9 said own repo | Complete — `shared-cli.md` now states own repo at `github.com/Wadeck/shared-cli`, consistent with D-9. |',
	'| SEC-04 | `launcher.config.json` UpdateCmd injection absent from STRIDE | Complete — T-07 added to threat model (Tampering, validate/restrict UpdateCmd, status Open). |',
	'| SEC-06 | `migrateIfNeeded` failure was fully silent — no user notification | Partially complete — now prints warning to stderr with old/new dir. Residual P-5 conflict documented above as SEC-06 residual. |',
	'| SEC-09 | `~/.npmrc` READ token absent from Assets table | Complete — Assets table now includes `~/.npmrc READ token` at Medium sensitivity. |',
];

fs.writeFileSync(path.join(dir, 'report.md'), lines.join('\n'), 'utf8');
console.log('Done');
